name: ez_qr
description: QR code (scan QRCode and picture) recognition （AndroidView/UiKitView）
version: 0.0.1
homepage: https://github.com/fogaiht/ez_qr

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.7.4
  permission_handler: ^6.1.1

dev_dependencies:
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: br.com.flutterando.ez_qr
        pluginClass: FlutterQrReaderPlugin
      ios:
        pluginClass: FlutterQrReaderPlugin
      